# rename this file to dir2feedSettings.py

# which directory to feedize. Use local absolute filesystem path.

whichDir = "/this/is/a/directory/accessible/from/web"

# HTTP path to whichDir. Don't add trailing slash.

httpPath = "http://www.example.com/path/to/whichDir"

# feedFile - where to output the resulting RSS feed. May or may not be in whichDir, doesn't matter.
feedFile = "/this/is/a/directory/accessible/from/web/dir2rss.xml"

# HTTP path (URL) to feedFile
httpFeedFile = "http://www.example.com/path/to/whichDir/dir2rss.xml"

# how many items from the directory to output to feed. May be as many or little as you want.
feedItemCount = 20

# feed title and description
feedTitle = "Directory listing feed generated by dir2feed"
feedDescription = "oh hai"
